export const TECHNOLOGIES = [
  ["typescript", "TypeScript"],
  ["react", "React"],
  ["nextjs", "Next.js"],
  ["nodejs", "Node.js"],
  ["go", "Go"],
  ["python", "Python"],
  ["postgresql", "PostgreSQL"],
  ["docker", "Docker"],
  ["kubernetes", "Kubernetes"],
  ["nestjs", "NestJS"],
  ["fastapi", "FastAPI"],
  ["tailwindcss", "Tailwind CSS"],
  ["rabbitmq", "RabbitMQ"],
  ["mongodb", "MongoDB"],
  ["azure", "Azure"],
  ["googlecloud", "Google Cloud"],
  ["argocd", "ArgoCD"],
  ["prometheus", "Prometheus"],
  ["grafana", "Grafana"],
  ["csharp", "C#"],
  ["githubactions", "GitHub Actions"],
  ["vscode", "VS Code"],
  ["jetbrains", "JetBrains"],
] as const;
export const SKILL_TECH = [
  ["react", "tailwindcss"],
  ["go", "nestjs", "fastapi"],
  ["python", "nodejs"],
  ["postgresql", "mongodb", "rabbitmq"],
  ["kubernetes", "docker", "argocd"],
  [],
];
